### ISSUE TITLE
break: only meaningful in a `for', `while', or `until' loop

### ISSUE THREAD

**Issue by donni106** [wangchucheng/git-repo-sync#6]
My GitHub Action argues about the `break` here:

https://github.com/wangchucheng/git-repo-sync/blob/63782025e80e84c48b25a1ee6bb9a22a3bd570d3/entrypoint.sh#L12

Weird is, that it worked for some time, and since then, this error occurs.
Anyone came across this before?

**Comment by donni106** [comment]
I guess the problem is, that I am triggering the workflow depending on another one with

```
on:
  workflow_run:
    workflows: ["other workflow name"]
    types:
      - completed
```

This way some env vars are not correct?

It works when running with

```
on:
  push:
    branches:
      - master
```
